AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      Runtime: python3.12
    Events:
      Api:
        Type: Api
        Properties:
        Path: /generate
        Method: GET